initial_increment: 50
fixed_memory: True
increment: 2
dataset: cifar100

model: icarl
convnet: rebuffi

classifier_config:
  type: fc
  use_bias: False

lr: 2.
weight_decay: 0.00005
scheduling:
  - 49
  - 63
lr_decay: 0.2
optimizer: sgd
epochs: 70
