model: ucir
convnet: rebuffi

batch_size: 512

initial_increment: 50
fixed_memory: True

scaling_factor: True
mimic_score: False
less_forget: True
lambda_schedule: True
ranking_loss: False

eval_type: nme

base_lambda: 5
nb_negatives: 2
margin_ranking: 0.5
imprinted_weights: True

lr: 0.4
weight_decay: 0.0005
scheduling:
  - 80
  - 120
lr_decay: 0.1
optimizer: sgd
epochs: 160
