model: ucir
convnet: rebuffi

initial_increment: 50
fixed_memory: True

mimic_score: False
less_forget: True
lambda_schedule: True
ranking_loss: False

postprocessor_config:
  type: heatedup
  first_value: 4.
  last_value: 16.
  nb_steps: 6

eval_type: nme

base_lambda: 5
nb_negatives: 2
margin_ranking: 0.5
imprinted_weights: True

lr: 0.1
weight_decay: 0.0005
scheduling:
  - 80
  - 120
lr_decay: 0.1
optimizer: sgd
epochs: 160
