model: ucir
convnet: rebuffi

increment: 10
fixed_memory: False

scaling_factor: True
lambda_schedule: True
distillation_loss: True
ranking_loss: True

base_lambda: 5
nb_negatives: 2
margin_ranking: 0.5
imprinted_weights: True


lr: 0.1
weight_decay: 0.0005
scheduling:
  - 80
  - 120
lr_decay: 0.1
optimizer: sgd
epochs: 160
