model: ucir
convnet: ucir

initial_increment: 50
fixed_memory: True

eval_type: cnn

scaling_factor: True
distillation_loss: True
lambda_schedule: True
ranking_loss: False

base_lambda: 5
nb_negatives: 2
margin_ranking: 0.5
imprinted_weights: True

lr: 0.1
weight_decay: 0.0005
scheduling:
  - 80
  - 120
lr_decay: 0.1
optimizer: sgd
epochs: 160
