model: ucir
convnet: rebuffi

initial_increment: 50
fixed_memory: True

scaling_factor: True
distillation_loss: False
lambda_schedule: False
ranking_loss: False

lr: 0.1
weight_decay: 0.0005
scheduling:
  - 80
  - 120
lr_decay: 0.1
optimizer: sgd
epochs: 160
