model: ucir
convnet: rebuffi

initial_increment: 50
increment: 10
fixed_memory: True

classifier_config:
  type: cosine

less_forget:
  scheduled_factor: true
  lambda: 5

postprocessor_config:
  initial_value: 1.0
  type: learned_scaling

lr: 0.1
weight_decay: 0.0005
scheduling:
  - 80
  - 120
lr_decay: 0.1
optimizer: sgd
epochs: 160

weight_generation:
  type: imprinted
  use_weights_norm: True
