model: ucir
convnet: rebuffi

initial_increment: 50
fixed_memory: True

scaling_factor: True
lambda_schedule: False
distillation_loss: True
ranking_loss: True

lr: 0.1
weight_decay: 0.0005
scheduling:
  - 80
  - 120
lr_decay: 0.1
optimizer: sgd
epochs: 160
