initial_increment: 500
fixed_memory: True
increment: 50
dataset: imagenet1000
validation: 0.1

model: bic
convnet: resnet18
convnet_config:
  nf: 64

batch_size: 64
memory_size: 20000

classifier_config:
  type: fc
  use_bias: False

temperature: 2.

lr: 0.025
weight_decay: 0.0001
scheduling:
  - 30
  - 60
  - 80
  - 90
lr_decay: 0.1
optimizer: sgd
epochs: 100
